### ISSUE TITLE
Stats.genetic_diversity raise "index out of bounds" exception

### ISSUE THREAD

**Issue by GBertholon** [Sakarah/GeneTipe#4]
When we call Stats.genetic_diversity with apparently good arguments (see in genetipe.ml) we just end up with :
`Fatal error: exception Invalid_argument("index out of bounds")`

**Comment by Gabzcr** [comment]
it's now corrected

**Comment by GBertholon** [comment]
Well in fact now it returns -nan...
Sorry it's not really corrected ^^
