### ISSUE TITLE
0% fitness while exact match because of float approximation

### ISSUE THREAD

**Issue by GBertholon** [Sakarah/GeneTipe#5]
When we tested the algorithm on the 10^x function with points from 0 to 10 we got the perfect match after simplification of the population while the fitness was still near 0%.
This is caused by float approximation with huge values.
Could we find ideas to fix that ?

**Comment by nchataing** [comment]
As I suggested, we can change the fitness function to determine the dy/y error. 

Fitness = sqrt [ sum {for x in points} abs((y-f(x))/y)^2 ]

**Comment by nchataing** [comment]
After changing that, we can see that the problem isn't due to float approximation yet to bad constant management.
